### ISSUE TITLE
tanh not working in browser demo

### ISSUE THREAD

**Issue by cristiano-belloni** [modlfo/vult#18]
Hello!
This:
```
fun saturate_table(x) @[table(size=10,min=0.0,max=6.0)] {
  return tanh(x);
}
```
Silently returns `Code: Error when compiling` without any further explanation.
If I change `tanh` to `sin` it works. Might it be that the demo version is old and doesn't support `tanh`? For sure it doesn't support `random` (but in that case, we get an Ace popup).

**Comment by cristiano-belloni** [comment]
(It works in the command line, btw)

**Comment by modlfo** [comment]
Right, sorry about that. This bites me from time to time. There's a bug in the converter from OCaml to Js https://github.com/ocsigen/js_of_ocaml/pull/561 and I forget that, until this fix is released, I have to manually patch the Js code. I'll be releasing an updated version later in the day.

**Comment by cristiano-belloni** [comment]
Cool, thanks. I'll +1 the issue so maybe they remember to release it :)

**Comment by modlfo** [comment]
I have fixed the problem in the web demo. Random should work as well. I just need to remember to patch the code every time.

**Comment by cristiano-belloni** [comment]
Confirmed for both, thanks!
