### ISSUE TITLE
Compiling Problem

### ISSUE THREAD

**Issue by kayji** [modlfo/vult#2]
Hello,

I tried to build Vult, but I've run into this problem:

Error: Signature mismatch:
       ...
       Values do not match:
         val compare :
           TypesVult.identifier ->
           TypesVult.identifier -> Ppx_deriving_runtime.int
       is not included in
         val compare : t -> t -> int
       File "src/typesUtil.ml", line 89, characters 7-14: Actual declaration
Command exited with code 2.

Has anybody experienced the same problem?

**Comment by kayji** [comment]
rm: cannot remove ‘vultc.native’: No such file or directory
rm: cannot remove ‘vultc.d.byte’: No such file or directory
+ ocamlfind ocamlc -c -package ocamlgraph -package str -package containers -I src -I src/util -I src/passes -o src/typesUtil.cmo src/typesUtil.ml
File "src/typesUtil.ml", line 94, characters 29-40:

**Comment by modlfo** [comment]
The problem is that the build command was not updated to use a new version of ppx_deriving. Now the build.sh script is up-to-date.
