### ISSUE TITLE
Install vult from native executbale

### ISSUE THREAD

**Issue by rafzael** [modlfo/vult#23]
Hello, 

I m trying to install vult from the native excutable for windows.
I try from mingW and windows terminal with 'start vultc' and my antivirus stop the install (then I ve desactivated it). I retried but nothing seems to happen.  
I tried by right click on it and run as admin but it oesn't seem to work.
When I try to compile vult code I get an error that tell me that vultc is not a valid command.

What am I doing wrong?

Thanks a lot.

**Comment by modlfo** [comment]
Let me try to understand. You downloaded the binary file from the releases page right? that contains a file called `vultc.exe`. That file is not an installer is just an executable. So from mingw you should be able to run it as `./vultc.exe` and you should get something like:
```
vult v0.3.31 - https://github.com/modlfo/vult
no input files
```

When you compile it yourself following the steps in the README. You will get an executable called `vultc.native`. And you should be able to call it as `./vultc.native`.

**Comment by rafzael** [comment]
OK, I was using start as a good old windows user :) And was thinking it was an installer that will let me use the command give on vultModules page like when installed with npm. 
I finally cd into the src of the modules, put the vultc.exe in it  and recompile the vult sources to get regenerated vultEngine.h and vultEngine.cpp with: 

./vultc.exe vult-src/VultEngine.vult -ccode -o VultEngine

Thank you very much, now I can compile from my windows session :) (much simpler for me than in my linux running on virtual box ).

**Comment by modlfo** [comment]
Great! I'll close this one then.
