### ISSUE TITLE
vultc.exe is missing from the Windows release binary

### ISSUE THREAD

**Issue by Murf** [modlfo/vult#31]
Can't find vulct.exe in the Windows binary zip

![image](https://user-images.githubusercontent.com/916793/83222817-a1481200-a1bc-11ea-8615-e5bafed69c28.png)

**Comment by Murf** [comment]
I found a compiled binary in 0.4.6 which I will use for the time being, can we please get the latest 0.4.10 build as well?

**Comment by modlfo** [comment]
Something went wrong when building that version in the windows machine. I will publish this weekend a new version and hopefully it will work correctly.

**Comment by Murf** [comment]
Thanks Leonardo!!!!

**Comment by modlfo** [comment]
There's a new release available.
