### ISSUE TITLE
V2 Rack browser crash

### ISSUE THREAD

**Issue by Chaircrusher** [modlfo/vult#40]
Windows 10
Rack version 219bbaf137d5dc70c96bd4206c3f8aad5524a81b

I was getting a crash trying to set up a default patch.
I run rack. Then click browser and type in 'cl' and boom it crashes.  I figured out Vult was the culprit by moving all the plugins out of Rack2/plugins, then adding them back in one at a time.   I'll put the crash stack in after the list of Modules.

I have a number of Rack modules I've built: 
AudibleInstruments
ESeries
ImpromptuModular 
squinkylabs-plug1
Befaco
FrozenWasteland
JW-Modules
Bidoo 
Fundamental
MindMeldModular
CountModula
HetrickCV
SubmarineFree VultModulesFree

[21.416 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
40:  0x0
39:  0x0
38: _C_specific_handler 0x7fffc199acc0
37: _chkstk 0x7fffc30081d0
36: RtlRestoreContext 0x7fffc2f95160
35: KiUserExceptionDispatcher 0x7fffc30072e0
34: ZN4rack10contextSetEPNS_7ContextE 0x6fa294d0
33: nvgFill 0x6f9fb7fd
32: ZN4rack6widget17FramebufferWidget6renderENS_4math3VecES3_NS2_4RectE 0x6fa9a6d8
31: ZN4rack6widget17FramebufferWidget4drawERKNS0_6Widget8DrawArgsE 0x6fa9b0a4
30: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x6fa9c9a8
29: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x6fa9cb4a
28: ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE 0x6fa9cdf6
27: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x6fa9c9a8
26: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x6fa9cb4a
25: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x6fa9c9a8
24: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x6fa9cb4a
23: ZN4rack3app7browser8ModelBox4drawERKNS_6widget6Widget8DrawArgsE 0x6fed49f0
22: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x6fa9c9a8
21: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x6fa9cb4a
20: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x6fa9c9a8
19: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x6fa9cb4a
18: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x6fa9c9a8
17: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x6fa9cb4a
16: ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi 0x6fa9c9a8
15: ZN4rack6widget6Widget4drawERKNS1

**Comment by modlfo** [comment]
It’s most probably the changes of the ABI. Are you using the latest build provided by Andrew or is it your own build from some other commit?

if you are using your own build from a different commit that could have caused the issue.

**Comment by Chaircrusher** [comment]
Getting the right build of Vult to go with the Rack I built (219bbaf137d5dc70c96bd4206c3f8aad5524a81b) fixes the error. Thanks!
