### ISSUE TITLE
Trummor2 bug / VCVRAck v2 Beta1 / OsX10.10.5

### ISSUE THREAD

**Issue by Motopomp** [modlfo/vult#41]
in a patch after saving and quitting Rack, when reopening the patch Trummor seems blocked, we have to put another in the patch and make the exchange, if I duplicate, I duplicate the bug with.
This is the "noise" party.
I made a little video.

https://user-images.githubusercontent.com/33150728/143846368-d2aa6a3b-9ad4-4c72-a60a-bc054f140fa7.mp4

**Comment by modlfo** [comment]
It looks to me like the bug I fixed that was affecting several modules. Do you have this release of the modules?
 
https://github.com/modlfo/VultModules/releases/tag/v2.0.0.Beta.1

**Comment by Motopomp** [comment]
I don't know if I am using this version, but I can replace them and see if it does…
thank you for your answer, I will give you news quickly

**Comment by Motopomp** [comment]
I just did the alternation, and everything seems to be back to normal, when the patch opens, no more blocking ......
thank you so much
