### ISSUE TITLE
Create reference manual

### ISSUE THREAD

**Issue by modlfo** [modlfo/vult#8]
Currently the only documentation of Vult is the tutorial but this does not cover all the functionality.

**Comment by johanrhodin** [comment]
What should a "reference manual" look like?

**Comment by modlfo** [comment]
I was thinking on two versions. One "extended" with the description of keywords, operands and builtin functions. The other a quick reference, with shorter descriptions and that can be embedded in panel next to the editor.

**Comment by modlfo** [comment]
The initial version of the manual is in the wiki https://github.com/modlfo/vult/wiki/Language-Reference

**Comment by danigb** [comment]
@modlfo vult is great! Congrats!

**Comment by modlfo** [comment]
@danigb Thanks!
